# Generated by Django 4.2.7 on 2025-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Unique registration number encoded in QR', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Attendee full name', max_length=100)),
                ('attended', models.BooleanField(default=False, help_text='Attendance status')),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Time when attendance was marked', null=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
